name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This step copies everything out of your subfolders and into a clean workspace
      - name: Restructure website files
        run: |
          mkdir staging
          cp -r images staging/
          cp -r PTBRepo/PTBWebsite/css staging/
          cp -r PTBRepo/PTBWebsite/html/* staging/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # This uploads our clean staging folder as the website root
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './staging'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

